### ISSUE TITLE
MAC Feature Request

### ISSUE THREAD

**Issue by MasterChief220** [omer-dogan/kali-whoami#21]
Um I just  wanted to ask why doesn't the MAC  address changer work if the option is included /?

**Comment by omer-dogan** [comment]
Please describe the situation in detail so that I can help you.

**Comment by MasterChief220** [comment]
> Please describe the situation in detail so that I can help you.

The MAC address and DNS changer don't work. I just wanted to ask whether they will be fixed in the near future or I need  to do that manually?

**Comment by omer-dogan** [comment]
A new update is about to come right now, but I haven't come across any bugs in mac or dns modules and this is the first time I've seen you have a problem. If you are using a virtual machine, you can retest on a new machine. My guess is there might be a problem with file access permissions.

**Comment by MasterChief220** [comment]
The gif you uploaded on the repository page that shows the tool being activated also show that the MAC address and DNS server changer don't work. So basically I have the exact same issue. All other tools work without any hitchance.

**Comment by omer-dogan** [comment]
Actually what you are describing is clearly written on the screen. DNS changer and IP changer cannot work at the same time because IP changer needs its own DNS to work, which technically changes your DNS address. The MAC changer cannot work in the virtual machine if there is no secondary network card. This is based on more detailed reasons. In short, this is not a bug.

**Comment by MasterChief220** [comment]
> Actually what you are describing is clearly written on the screen. DNS changer and IP changer cannot work at the same time because IP changer needs its own DNS to work, which technically changes your DNS address. The MAC changer cannot work in the virtual machine if there is no secondary network card. This is based on more detailed reasons. In short, this is not a bug.

Okay thanks for your help then.
