### ISSUE TITLE
[Question] Any chance this will work on Ubuntu ?

### ISSUE THREAD

**Issue by kevinadhiguna** [omer-dogan/kali-whoami#22]
**Is your feature request related to a problem? Please describe.**
Hi, thanks for this amazing tool !

I understand that this tool is meant for Kali Linux but it would be great if it works on Ubuntu/Debian as well imho.

**Describe the feature you'd like**
Is this tool compatible with Ubuntu as well? Or maybe in future ?

Any replies are appreciated !

**Comment by omer-dogan** [comment]
Hi, actually Kali was just a test. As I mentioned on the homepage, I will support more distros soon. I'm currently working on design and usability improvements. Thanks for your thoughts on the vehicle. If you tell the people around leave a star for the project, they will help me a lot.  I wish you healthy days!

**Comment by kevinadhiguna** [comment]
Thanks @omer-dogan, I hope you and yours are well!
